# Generated by Django 5.1 on 2024-08-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NewsViews',
        ),
    ]
