# Generated by Django 5.1 on 2024-08-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_count_delete_newsviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
