# Generated by Django 5.1 on 2024-08-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
