# Generated by Django 5.1 on 2024-09-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreaming',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
